config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do 
    put :sort, on: :collection
  end
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
# angular is for demo and info purposes

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'


  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end

  mount ActionCable.server => '/cable'
  
	root to: 'pages#home' 

end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator  %> | <a href="https://github.com/JustimusPrime"><%= fa_icon "github" %></a> </p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Justin Murray</h3>
              <nav class="nav nav-masthead app-nav">
                <%= nav_helper 'nav-link', 'span' %>
                <%= login_helper 'nav-link' %>
              </nav>
            </div>
          </header>

app/views/shared/_blog.nav.html.erb
    <div class="blog-masthead">
      <div class="container">
        <nav class="nav blog-nav">
           <%= link_to "Home", root_path, class: 'nav-link' %>
           <%= link_to "About", about_me_path, class: 'nav-link' %>
           <%= link_to "Contact", contact_path, class: 'nav-link' %>
           <%= link_to "Blog", blogs_path, class: 'nav-link' %>
           <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
           <%= login_helper 'nav-link' %>
        </nav>
      </div>
    </div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Ramblings of a Coder</h1>
    <p class="lead blog-description">OH NO YOU FOUND MY SUPER SECRET BLOG!!!!<br>This is a blog with full CRUD functionality that I should write in more<br>
    I'm also not nuts about the styling to be quite honest, which is why it's so super hidden</p>
      <span>
        <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %> |       
      </span>
      <span>
        <%= link_to  "Topic", topics_path %>
      </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg  blog-nav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="container">
    <%= link_to "Justin Murray", root_path, class: "navbar-brand" %>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav mr-auto blog-nav-text">
        <%= nav_helper 'nav-link', 'li' %>
        <%= login_helper 'nav-link' %>
      </ul>
    </div>
  </div>






</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>I was raised in small-town Iowa, then became an adult in New York City. Whether it was academia, statistical analysis or stand-up comedy or programming, I have always been fascinated with creation and perfection; making something then the endless pursuit of perfecting it. </p>
  </div>

  
  <%= source_helper("alert alert-info blog-sidebar-source") %>
  

  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p> <%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/JustimusPrime"><%= fa_icon "github" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
      <li><a href="#"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://www.linkedin.com/in/justin-murray-b116941b/"><%= fa_icon "linkedin" %></a></li>
    </ol>
  </div>
</div>

<!-- only keep icons you have links to in social media -->

app/views/shared/_nav.html.erb
    <div class="<%= location %>">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_me_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Blog", blogs_path %></div>
      <div><%= link_to "Portfolio", portfolios_path %></div>
    </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted footer-text">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> |
      <a href="#">Back to top</a>
    </p>
    <p>
    <span><%= copyright_generator %> | </span><a href="https://github.com/JustimusPrime"><%= fa_icon "github" %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center port-container">
  <div class="container port-container">
    <h1 class="jumbotron-heading port-heading">My Portfolio</h1>
    <p class="lead text-muted port-header-subtitle"><span>A collection of the glorious things I have made<br>Adding projects...check back soon!<span></p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<nav id="navbar-primary" class="navbar navbar-expand-lg navbar-light portfolio-nav" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav mr-auto">
        <li class="active"><%= link_to "About", about_me_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Blog", blogs_path %></li>
        <li><a href="http://www.thejustinmurray.com"><img id="logo-navbar-middle" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/32877/logo-thing.png" width="200" alt="Logo Thing main logo"></a></li>
        <li><%= link_to "Portfolio", portfolios_path %></li>
        <li><%= link_to "Steeler News", tech_news_path %></li>
        <li><%= login_helper 'nav-link' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>